master:
  image: redis:latest
slave:
  image: redis:latest
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
  links:
    - master:redis-master
    - slave
phpredisadmin:
  image: erikdubbelboer/phpredisadmin:latest
  restart: always
  links:
    - master:master
  environment:
    - VIRTUAL_HOST=${PHPREDISADMIN_URL}
    - REDIS_1_HOST=master
